// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Topbar from "@/components/Topbar";
import "./globals.css";
import { VCSProvider } from "@/components/VCSProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body /*className={inter.className}*/>
        <VCSProvider>
          <Topbar/>
          {children}
        </VCSProvider>
      </body>
    </html>
  );
}
